### PR TITLE
BACKLOG-16221: Flushing all caches.

### PR DESCRIPTION
**Pull request by XiangYuHe**
## JIRA

https://jira.jahia.org/browse/BACKLOG-16221

## Description

Updated to only flush the nodes involved by path:
The sitemap, sitemap resource, and the jnt pages that are used for canonical URLs.

### CODE REVIEW

**Review by tdraier — CHANGES_REQUESTED** [review]
As discussed last week, please find the proper entries to be flushed.

**Comment by XiangYuHe** [comment]
> As discussed last week, please find the proper entries to be flushed.

Updated to flush only the nodes involved: (per their path)
The sitemap, sitemap resource, and the jnt page that is used for canonical URLs

**Comment by tdraier** [comment]
I don't understand the use case and the need to flush any HTML cache. I've only tested a simple sitemap, with a "dedicated" sitemap on a page. The only cache entry that get generated in my cache, when I call all sitemap, is this : 
 
```en@@/sites/digitall/sitemap@@canonicalPath@@default@@xml@@221029189[u:guest]@@page@@false@@@@{}@@@@4bef6b09-3aa9-47c6-b07f-9c80eb2ae335@@@@digitall:null@@@@@@@@@@```

When I change the sitemap root URL, from xxx to yyy, I agree that sitemap are still getting the old url - clicking on "flush cache" correctly refresh the files ( http://yyy/sitemap-lang.xml  ), but not the http://yyy/sitemap.xml itself. Actually it seems that it flushes the sitemap.xml file if a sitemap resource was previously generated, but not if no file is present. As far as i understand, the cacheNode.remove in CacheUtils flush the /sites/digitall/sitemap following the dependencies. If there's no file, no cache is flushed.

But in all cases, flushing the single cache entry at /sites/digitall/sitemap flush the sitemap - that's anyway the only entry I have, so flushing other do not seem very useful. Since no other cache entry is present, I don't see how flushing them would change anything.

If you have any description of the issue, that would help.

**Comment by XiangYuHe** [comment]
Yes you are correct flushing the "/sites/<sitekey>/sitemap" will flush for the sitemap entries.
But there is a scenario for the canonical URL showing on site pages header that also uses the root URL: that is not flushed when the "/sites/<sitekey>/sitemap" instead we needed to flush the jnt:page to flush the header entries.

**Comment by tdraier** [comment]
Ok understand, I did not know about these canonical urls in the pages. Agree that to refresh them you need to flush the pages cache. But the thing is that I don't see anywhere in the code what is adding these canonical/alternate urls in the pages ? Actually even if sitemap module is stopped I still have canonical/alternate URLs in the page. If sitemap is not adding these, it cannot know if/where they are added, and it cannot flush them neither. So apart from displaying a message to the user that he might have to flush some cache, it cannot do much more.

**Comment by tdraier** [comment]
Edit : I found that it's site-settings-seo which is adding these urls through a filter on page. So flushing html cache for pages is "ok" , even though it should be the role of site-settings-seo to do that when the root url is changed. 

However, It's strange that we don't have it on other node types than jnt:page - i would have expected to have it on any full page renderer node type, like news - and in that case we should also flush them.

**Review by tdraier — APPROVED** [review]

**Comment by rknj** [comment]
@gflores-jahia @XiangYuHe don't we also have canonical urls on content of type `jmix:mainResource` ?

**Comment by XiangYuHe** [comment]
> @gflores-jahia @XiangYuHe don't we also have canonical urls on content of type `jmix:mainResource` ?

No based on the @Active
We are only setApplyOnNodeTypes on jnt page

**Comment by XiangYuHe** [comment]
> Edit : I found that it's site-settings-seo which is adding these urls through a filter on page. So flushing html cache for pages is "ok" , even though it should be the role of site-settings-seo to do that when the root url is changed.
> 
> However, It's strange that we don't have it on other node types than jnt:page - i would have expected to have it on any full page renderer node type, like news - and in that case we should also flush them.

I am not sure the initial design but the target is jnt:page

**Pull request merged**
